### ISSUE TITLE
Make news scroll on the top right editable

### ISSUE THREAD

**Issue by jayadeepk** [sail-iitg/alumniportal#12]
Admin should be able to edit contents of news scroll widget displayed on the top right of any page.

**Comment by ranka47** [comment]
Check it once.

**Comment by jayadeepk** [comment]
Reviewed your commit https://github.com/sail-iitg/alumniportal/commit/b62b9. Good to get contents from News table. I've removed the image and added news content in the rolling news here https://github.com/sail-iitg/alumniportal/commit/9c870.
