### ISSUE TITLE
Another Add New form not displayed after submitting one in Edit Profile

### ISSUE THREAD

**Issue by jayadeepk** [sail-iitg/alumniportal#2]
After submitting Add New form in Edit Profile under all tabs except 'Personal', the data is successfully saved but the page doesn't display another Add New form until the page is refreshed manually.

Before submitting the form:
![image](https://cloud.githubusercontent.com/assets/5885220/11735396/c489a076-9fe6-11e5-9258-b21ac214b80c.png)

After submitting the form, before refreshing:
![image](https://cloud.githubusercontent.com/assets/5885220/11735486/afb00054-9fe7-11e5-878a-ca04a32ce009.png)

**Comment by ranka47** [comment]
If sometimes "messages.success" or "messages.error" does not appear but user constantly clicks on Save Changes then many tabs get added. To add more User has to refresh the page or come back to the tab by clicking on it. 
Showing "Saved" and list of the data added was like a confirmation page.

**Comment by jayadeepk** [comment]
@ranka47 The first time users might find it difficult to add multiple projects. I'll leave this issue open.

**Comment by ranka47** [comment]
@jayadeepk Is it okay now? I think the issue should be closed now.

**Comment by jayadeepk** [comment]
@ranka47 Yeah, it was fixed.
