### ISSUE TITLE
Deleting education/iitg/project/achivement/job in Edit Profile

### ISSUE THREAD

**Issue by jayadeepk** [sail-iitg/alumniportal#3]
The proposed location for delete button is shown in red in the image below:
![screenshot from 2015-12-11 09 20 41](https://cloud.githubusercontent.com/assets/5885220/11735587/d85c1122-9fe8-11e5-8f8d-b44afbd17d6e.png)

**Comment by ranka47** [comment]
I have pushed the changes solving the issue. Review it.

**Comment by jayadeepk** [comment]
@ranka47 Works good.

**Comment by jayadeepk** [comment]
Works good.
