### ISSUE TITLE
Error while creating activity

### ISSUE THREAD

**Issue by yashbelhe** [sail-iitg/alumniportal#6]
When I created an activity as a normal user (not an admin) I got this error :
<img width="1440" alt="screen shot 2016-01-24 at 2 30 40 pm" src="https://cloud.githubusercontent.com/assets/5306218/12535389/8ad53b90-c2a7-11e5-9d09-f8f30f987bb4.png">

**Comment by jayadeepk** [comment]
@thezobot1 I am able to create activity as a non-admin user with filled profile. Can you provide steps to reproduce this bug?
